name: buildtex

on:
  push:
    branches: main
    paths: [docs/**]
  pull_request:
    branches: main
    paths: [docs/**]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed LaTeX files
        id: latex-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- docs/**/*.tex | xargs)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          CHANGED_FILENAMES=$(for file in $CHANGED_FILES; do basename "$file"; done | xargs)
          echo "CHANGED_FILENAMES=$CHANGED_FILENAMES" >> $GITHUB_ENV
          FILE_COUNT=$(echo $CHANGED_FILENAMES | wc -w)
          if [ $FILE_COUNT -gt 1 ]; then
            PLURAL_S='s'
          else
            PLURAL_S=''
          fi
          echo "PLURAL_S=$PLURAL_S" >> $GITHUB_ENV
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-medium
      - name: Compile LaTeX Files
        working-directory: docs
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            dir=$(dirname "$file" | cut -d'/' -f2-)
            make -B "$dir/$(basename "$file" .tex).pdf"
          done
      - name: Commit and push PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add/Update PDF${{ env.PLURAL_S }} for changed LaTeX file${{ env.PLURAL_S }}: ${{ env.CHANGED_FILENAMES }}'
          file_pattern: 'docs/*.pdf'
          branch: main
