name: Clang Format Check

on:
  push:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "**/*.hpp,**/*.cpp"
          excludes: "**/qdldl.hpp"
          style: file
