name: CTest

on:
  push:

jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
