name: CTest

on:
  push:

jobs:
  test-project:
    name: Test Project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            CMAKE_BUILD_TYPE=Release

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Release
